In [1]:
import pandas as pd
import numpy as np

import ast

In [2]:
df = pd.read_csv('talks_info.csv')
df

,_id,duration,event,likes,page_url,published_date,recorded_date,related_videos,speakers,subtitle_languages,summary,title,topics,transcript,views,youtube_video_code
0,21,992,TED2006,17K,https://www.ted.com/talks/mena_trott_meet_the_...,2006-08-25T00:11:00Z,2006-02-23,"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[{""name"":""Mena Trott"",""occupation"":""Blogger; c...","[{""name"":""English"",""code"":""en""},{""name"":""Vietn...","The founding mother of the blog revolution, Mo...",Meet the founder of the blog revolution,"[{""id"":""4"",""name"":""culture""},{""id"":""13"",""name""...","Over the past couple of days, as I've been pre...",589115,RlBTxuWCuL8
1,1,957,TED2006,110K,https://www.ted.com/talks/al_gore_averting_the...,2006-06-27T00:11:00Z,2006-02-25,"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[{""name"":""Al Gore"",""occupation"":""Climate advoc...","[{""name"":""Greek"",""code"":""el""},{""name"":""Gujarat...",With the same humor and humanity he exuded in ...,Averting the climate crisis,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...","Thank you so much, Chris. And it's truly a gre...",3671801,rDiGYuQicpA
2,7,1266,TED2006,60K,https://www.ted.com/talks/david_pogue_simplici...,2006-06-27T00:11:00Z,2006-02-24,"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[{""name"":""David Pogue"",""occupation"":""Technolog...","[{""name"":""Greek"",""code"":""el""},{""name"":""English...",New York Times columnist David Pogue takes aim...,Simplicity sells,"[{""id"":""10"",""name"":""technology""},{""id"":""36"",""n...","(Music: ""The Sound of Silence,"" Simon &amp; Ga...",2008487,NEjZt0y6OOw
3,47,1126,TEDGlobal 2005,80K,https://www.ted.com/talks/david_deutsch_chemic...,2006-09-12T00:11:00Z,2005-07-14,"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[{""name"":""David Deutsch"",""occupation"":""Physici...","[{""name"":""Greek"",""code"":""el""},{""name"":""English...",Legendary scientist David Deutsch puts theoret...,Chemical scum that dream of distant quasars,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...",We've been told to go out on a limb and say so...,2694257,gQliI_WGaGk
4,55,1524,TED2006,14K,https://www.ted.com/talks/jehane_noujaim_my_wi...,2006-07-25T00:11:00Z,2006-02-26,"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[{""name"":""Jehane Noujaim"",""occupation"":""Filmma...","[{""name"":""English"",""code"":""en""},{""name"":""Vietn...",Jehane Noujaim unveils her 2006 TED Prize wish...,My wish: A global day of film,"[{""id"":""4"",""name"":""culture""},{""id"":""6"",""name"":...",I can't help but this wish: to think about whe...,489757,QCFSrb6B5nw
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5626,95714,278,TED-Ed,5.8K,https://www.ted.com/talks/lyla_latif_the_true_...,2022-07-21T15:04:36Z,2022-07-21,"[""79294"",""24262"",""84056""]","[{""name"":""Lyla Latif"",""occupation"":""Educator""}]","[{""name"":""English"",""code"":""en""},{""name"":""Arabi...","In 2020, Mali produced over 71 tons of gold— a...",The true cost of gold,"[{""id"":""18"",""name"":""business""},{""id"":""19"",""nam...",Gold is one of Earth’s most valuable resources...,195168,1nglN3mfZUw
5627,95710,940,TEDxSeattle,10K,https://www.ted.com/talks/trish_millines_dziko...,2022-07-21T15:13:53Z,2021-11-20,"[""83539"",""46386"",""52190"",""1667"",""1710"",""2050""]","[{""name"":""Trish Millines Dziko"",""occupation"":""...","[{""name"":""English"",""code"":""en""},{""name"":""Arabi...","Forget home economics and standardized tests, ...",How schools can nurture every student's genius,"[{""id"":""52"",""name"":""education""},{""id"":""53"",""na...",Let me tell you about the fifth-grade students...,356620,NaN
5628,95451,1048,TED2022,12K,https://www.ted.com/talks/david_wengrow_a_new_...,2022-07-22T14:36:05Z,2022-04-10,"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]","[{""name"":""David Wengrow"",""occupation"":""Archaeo...","[{""name"":""English"",""code"":""en""},{""name"":""Arabi...",What if the commonly accepted narratives about...,A new understanding of human history and the r...,"[{""id"":""4"",""name"":""culture""},{""id"":""81"",""name""...","In the summer of 2014, I was in Iraqi Kurdista...",412825,8SJi0sHrEI4
5629,95708,651,TED2022,7.2K,https://www.ted.com/talks/dan_widmaier_the_fut...,2022-07-25T14:47:14Z,2022-04-10,"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]","[{""name"":""Dan Widmaier"",""occupation"":""Biomater...","[{""name"":""English"",""code"":""en""}]",Your closet is likely full of all kinds of mat...,The future of fashion -- made from mushrooms,"[{""id"":""5"",""name"":""environment""},{""id"":""8"",""na...","I'm a proud lifelong nerd, and I have a PhD in...",240375,OcdumFcGdfU
5630,95709,649,TED2022,4.5K,https://www.ted.com/talks/scott_fitsimones_cou...,2022-07-26T15:04:59Z,2022-04-10,"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","[{""name"":""Scott Fitsimones"",""occupation"":""Expe...","[{""name"":""English"",""code"":""en""}]","Could DAOs, or ""decentralized autonomous organ...",Could a DAO build the next great city?,"[{""id"":""45"",""name"":""cities""},{""id"":""51"",""name""...",How do you start a new city? Turns out it's no...,151529,zTStDvUtQWc

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5631 entries, 0 to 5630
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _id                 5631 non-null   int64
 1   duration            5631 non-null   int64
 2   event               5630 non-null   object
 3   likes               5631 non-null   object
 4   page_url            5631 non-null   object
 5   published_date      5631 non-null   object
 6   recorded_date       5629 non-null   object
 7   related_videos      5631 non-null   object
 8   speakers            5631 non-null   object
 9   subtitle_languages  5631 non-null   object
 10  summary             5631 non-null   object
 11  title               5631 non-null   object
 12  topics              5631 non-null   object
 13  transcript          4983 non-null   object
 14  views               5631 non-null   int64
 15  youtube_video_code  5462 non-null   object
dtypes: int64(3), object(13)
memory usage: 704.0+ KB

In [4]:
df.columns

Index(['_id', 'duration', 'event', 'likes', 'page_url', 'published_date',
       'recorded_date', 'related_videos', 'speakers', 'subtitle_languages',
       'summary', 'title', 'topics', 'transcript', 'views',
       'youtube_video_code'],
      dtype='object')

In [5]:
## Which columns to keep
# _id
# event
# speakers
# related videos
# summary
# topics
# youtube_video_code

In [6]:
df.rename(columns = {'_id':'ID', 'youtube_video_code': 'Video_code'}, inplace = True)
df.head()

,ID,duration,event,likes,page_url,published_date,recorded_date,related_videos,speakers,subtitle_languages,summary,title,topics,transcript,views,Video_code
0,21,992,TED2006,17K,https://www.ted.com/talks/mena_trott_meet_the_...,2006-08-25T00:11:00Z,2006-02-23,"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[{""name"":""Mena Trott"",""occupation"":""Blogger; c...","[{""name"":""English"",""code"":""en""},{""name"":""Vietn...","The founding mother of the blog revolution, Mo...",Meet the founder of the blog revolution,"[{""id"":""4"",""name"":""culture""},{""id"":""13"",""name""...","Over the past couple of days, as I've been pre...",589115,RlBTxuWCuL8
1,1,957,TED2006,110K,https://www.ted.com/talks/al_gore_averting_the...,2006-06-27T00:11:00Z,2006-02-25,"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[{""name"":""Al Gore"",""occupation"":""Climate advoc...","[{""name"":""Greek"",""code"":""el""},{""name"":""Gujarat...",With the same humor and humanity he exuded in ...,Averting the climate crisis,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...","Thank you so much, Chris. And it's truly a gre...",3671801,rDiGYuQicpA
2,7,1266,TED2006,60K,https://www.ted.com/talks/david_pogue_simplici...,2006-06-27T00:11:00Z,2006-02-24,"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[{""name"":""David Pogue"",""occupation"":""Technolog...","[{""name"":""Greek"",""code"":""el""},{""name"":""English...",New York Times columnist David Pogue takes aim...,Simplicity sells,"[{""id"":""10"",""name"":""technology""},{""id"":""36"",""n...","(Music: ""The Sound of Silence,"" Simon &amp; Ga...",2008487,NEjZt0y6OOw
3,47,1126,TEDGlobal 2005,80K,https://www.ted.com/talks/david_deutsch_chemic...,2006-09-12T00:11:00Z,2005-07-14,"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[{""name"":""David Deutsch"",""occupation"":""Physici...","[{""name"":""Greek"",""code"":""el""},{""name"":""English...",Legendary scientist David Deutsch puts theoret...,Chemical scum that dream of distant quasars,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...",We've been told to go out on a limb and say so...,2694257,gQliI_WGaGk
4,55,1524,TED2006,14K,https://www.ted.com/talks/jehane_noujaim_my_wi...,2006-07-25T00:11:00Z,2006-02-26,"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[{""name"":""Jehane Noujaim"",""occupation"":""Filmma...","[{""name"":""English"",""code"":""en""},{""name"":""Vietn...",Jehane Noujaim unveils her 2006 TED Prize wish...,My wish: A global day of film,"[{""id"":""4"",""name"":""culture""},{""id"":""6"",""name"":...",I can't help but this wish: to think about whe...,489757,QCFSrb6B5nw

In [7]:
df = df[['ID', 'event', 'speakers', 'related_videos', 'summary','title', 'topics', 'Video_code']]
df.head(1)

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,"[{""name"":""Mena Trott"",""occupation"":""Blogger; c...","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","The founding mother of the blog revolution, Mo...",Meet the founder of the blog revolution,"[{""id"":""4"",""name"":""culture""},{""id"":""13"",""name""...",RlBTxuWCuL8

In [8]:
df.columns

Index(['ID', 'event', 'speakers', 'related_videos', 'summary', 'title',
       'topics', 'Video_code'],
      dtype='object')

In [9]:
df.iloc[0]

ID                                                               21
event                                                       TED2006
speakers          [{"name":"Mena Trott","occupation":"Blogger; c...
related_videos             ["144","1282","1379","87","2302","2638"]
summary           The founding mother of the blog revolution, Mo...
title                       Meet the founder of the blog revolution
topics            [{"id":"4","name":"culture"},{"id":"13","name"...
Video_code                                              RlBTxuWCuL8
Name: 0, dtype: object

In [10]:
df.isnull().sum()

ID                  0
event               1
speakers            0
related_videos      0
summary             0
title               0
topics              0
Video_code        169
dtype: int64

In [11]:
df.dropna(inplace = True)

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\1791587065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace = True)

In [12]:
df.duplicated().sum()

0

In [13]:
df.speakers[0]

'[{"name":"Mena Trott","occupation":"Blogger; cofounder, Six Apart"}]'

In [14]:
def convert(obj):
    L = []
    for i in ast.literal.eval(obj):
        L.append(i['name'])
    return L

In [15]:
import ast

In [16]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [17]:
df['speakers'] = df['speakers'].apply(convert)

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\476451681.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['speakers'] = df['speakers'].apply(convert)

In [18]:
df['speakers']

0             [Mena Trott]
1                [Al Gore]
2            [David Pogue]
3          [David Deutsch]
4         [Jehane Noujaim]
               ...
5625     [Catherine Price]
5626          [Lyla Latif]
5628       [David Wengrow]
5629        [Dan Widmaier]
5630    [Scott Fitsimones]
Name: speakers, Length: 5462, dtype: object

In [19]:
df.head()

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,[Mena Trott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","The founding mother of the blog revolution, Mo...",Meet the founder of the blog revolution,"[{""id"":""4"",""name"":""culture""},{""id"":""13"",""name""...",RlBTxuWCuL8
1,1,TED2006,[Al Gore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",With the same humor and humanity he exuded in ...,Averting the climate crisis,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...",rDiGYuQicpA
2,7,TED2006,[David Pogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",New York Times columnist David Pogue takes aim...,Simplicity sells,"[{""id"":""10"",""name"":""technology""},{""id"":""36"",""n...",NEjZt0y6OOw
3,47,TEDGlobal 2005,[David Deutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",Legendary scientist David Deutsch puts theoret...,Chemical scum that dream of distant quasars,"[{""id"":""3"",""name"":""climate change""},{""id"":""4"",...",gQliI_WGaGk
4,55,TED2006,[Jehane Noujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",Jehane Noujaim unveils her 2006 TED Prize wish...,My wish: A global day of film,"[{""id"":""4"",""name"":""culture""},{""id"":""6"",""name"":...",QCFSrb6B5nw

In [20]:
df['topics'][0]

'[{"id":"4","name":"culture"},{"id":"13","name":"design"},{"id":"18","name":"business"},{"id":"37","name":"entertainment"},{"id":"42","name":"software"},{"id":"85","name":"storytelling"},{"id":"86","name":"communication"},{"id":"87","name":"community"}]'

In [21]:
df['topics'] = df['topics'].apply(convert)

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\1502975548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['topics'] = df['topics'].apply(convert)

In [22]:
df['topics']

0       [culture, design, business, entertainment, sof...
1       [climate change, culture, environment, global ...
2       [technology, computers, entertainment, media, ...
3       [climate change, culture, environment, global ...
4       [culture, global issues, entertainment, social...
                              ...
5625    [science, health, psychology, happiness, motiv...
5626    [business, corruption, education, Africa, hist...
5628    [culture, history, anthropology, humanity, anc...
5629    [environment, science, sustainability, innovat...
5630    [cities, urban planning, future, democracy, mo...
Name: topics, Length: 5462, dtype: object

In [23]:
df

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,[Mena Trott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","The founding mother of the blog revolution, Mo...",Meet the founder of the blog revolution,"[culture, design, business, entertainment, sof...",RlBTxuWCuL8
1,1,TED2006,[Al Gore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",With the same humor and humanity he exuded in ...,Averting the climate crisis,"[climate change, culture, environment, global ...",rDiGYuQicpA
2,7,TED2006,[David Pogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",New York Times columnist David Pogue takes aim...,Simplicity sells,"[technology, computers, entertainment, media, ...",NEjZt0y6OOw
3,47,TEDGlobal 2005,[David Deutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",Legendary scientist David Deutsch puts theoret...,Chemical scum that dream of distant quasars,"[climate change, culture, environment, global ...",gQliI_WGaGk
4,55,TED2006,[Jehane Noujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",Jehane Noujaim unveils her 2006 TED Prize wish...,My wish: A global day of film,"[culture, global issues, entertainment, social...",QCFSrb6B5nw
...,...,...,...,...,...,...,...,...
5625,95500,TED2022,[Catherine Price],"[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",Have you had your daily dose of fun? It's not ...,Why fun is the secret to a healthier life,"[science, health, psychology, happiness, motiv...",iMBJrvEwv8s
5626,95714,TED-Ed,[Lyla Latif],"[""79294"",""24262"",""84056""]","In 2020, Mali produced over 71 tons of gold— a...",The true cost of gold,"[business, corruption, education, Africa, hist...",1nglN3mfZUw
5628,95451,TED2022,[David Wengrow],"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",What if the commonly accepted narratives about...,A new understanding of human history and the r...,"[culture, history, anthropology, humanity, anc...",8SJi0sHrEI4
5629,95708,TED2022,[Dan Widmaier],"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",Your closet is likely full of all kinds of mat...,The future of fashion -- made from mushrooms,"[environment, science, sustainability, innovat...",OcdumFcGdfU
5630,95709,TED2022,[Scott Fitsimones],"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","Could DAOs, or ""decentralized autonomous organ...",Could a DAO build the next great city?,"[cities, urban planning, future, democracy, mo...",zTStDvUtQWc

In [24]:
df['summary'] = df['summary'].apply(lambda x: x.split())
df

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\470539913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['summary'] = df['summary'].apply(lambda x: x.split())

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,[Mena Trott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[The, founding, mother, of, the, blog, revolut...",Meet the founder of the blog revolution,"[culture, design, business, entertainment, sof...",RlBTxuWCuL8
1,1,TED2006,[Al Gore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[With, the, same, humor, and, humanity, he, ex...",Averting the climate crisis,"[climate change, culture, environment, global ...",rDiGYuQicpA
2,7,TED2006,[David Pogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[New, York, Times, columnist, David, Pogue, ta...",Simplicity sells,"[technology, computers, entertainment, media, ...",NEjZt0y6OOw
3,47,TEDGlobal 2005,[David Deutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[Legendary, scientist, David, Deutsch, puts, t...",Chemical scum that dream of distant quasars,"[climate change, culture, environment, global ...",gQliI_WGaGk
4,55,TED2006,[Jehane Noujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[Jehane, Noujaim, unveils, her, 2006, TED, Pri...",My wish: A global day of film,"[culture, global issues, entertainment, social...",QCFSrb6B5nw
...,...,...,...,...,...,...,...,...
5625,95500,TED2022,[Catherine Price],"[""91710"",""90821"",""76335"",""1607"",""570"",""779""]","[Have, you, had, your, daily, dose, of, fun?, ...",Why fun is the secret to a healthier life,"[science, health, psychology, happiness, motiv...",iMBJrvEwv8s
5626,95714,TED-Ed,[Lyla Latif],"[""79294"",""24262"",""84056""]","[In, 2020,, Mali, produced, over, 71, tons, of...",The true cost of gold,"[business, corruption, education, Africa, hist...",1nglN3mfZUw
5628,95451,TED2022,[David Wengrow],"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]","[What, if, the, commonly, accepted, narratives...",A new understanding of human history and the r...,"[culture, history, anthropology, humanity, anc...",8SJi0sHrEI4
5629,95708,TED2022,[Dan Widmaier],"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]","[Your, closet, is, likely, full, of, all, kind...",The future of fashion -- made from mushrooms,"[environment, science, sustainability, innovat...",OcdumFcGdfU
5630,95709,TED2022,[Scott Fitsimones],"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","[Could, DAOs,, or, ""decentralized, autonomous,...",Could a DAO build the next great city?,"[cities, urban planning, future, democracy, mo...",zTStDvUtQWc

In [25]:
df['title'] = df['title'].apply(lambda x:x.split())
df

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\1923540356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].apply(lambda x:x.split())

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,[Mena Trott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[The, founding, mother, of, the, blog, revolut...","[Meet, the, founder, of, the, blog, revolution]","[culture, design, business, entertainment, sof...",RlBTxuWCuL8
1,1,TED2006,[Al Gore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[With, the, same, humor, and, humanity, he, ex...","[Averting, the, climate, crisis]","[climate change, culture, environment, global ...",rDiGYuQicpA
2,7,TED2006,[David Pogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[New, York, Times, columnist, David, Pogue, ta...","[Simplicity, sells]","[technology, computers, entertainment, media, ...",NEjZt0y6OOw
3,47,TEDGlobal 2005,[David Deutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[Legendary, scientist, David, Deutsch, puts, t...","[Chemical, scum, that, dream, of, distant, qua...","[climate change, culture, environment, global ...",gQliI_WGaGk
4,55,TED2006,[Jehane Noujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[Jehane, Noujaim, unveils, her, 2006, TED, Pri...","[My, wish:, A, global, day, of, film]","[culture, global issues, entertainment, social...",QCFSrb6B5nw
...,...,...,...,...,...,...,...,...
5625,95500,TED2022,[Catherine Price],"[""91710"",""90821"",""76335"",""1607"",""570"",""779""]","[Have, you, had, your, daily, dose, of, fun?, ...","[Why, fun, is, the, secret, to, a, healthier, ...","[science, health, psychology, happiness, motiv...",iMBJrvEwv8s
5626,95714,TED-Ed,[Lyla Latif],"[""79294"",""24262"",""84056""]","[In, 2020,, Mali, produced, over, 71, tons, of...","[The, true, cost, of, gold]","[business, corruption, education, Africa, hist...",1nglN3mfZUw
5628,95451,TED2022,[David Wengrow],"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]","[What, if, the, commonly, accepted, narratives...","[A, new, understanding, of, human, history, an...","[culture, history, anthropology, humanity, anc...",8SJi0sHrEI4
5629,95708,TED2022,[Dan Widmaier],"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]","[Your, closet, is, likely, full, of, all, kind...","[The, future, of, fashion, --, made, from, mus...","[environment, science, sustainability, innovat...",OcdumFcGdfU
5630,95709,TED2022,[Scott Fitsimones],"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","[Could, DAOs,, or, ""decentralized, autonomous,...","[Could, a, DAO, build, the, next, great, city?]","[cities, urban planning, future, democracy, mo...",zTStDvUtQWc

In [26]:
#df.drop(columns = ['event'], axis = 1, inplace = True)
df

,ID,event,speakers,related_videos,summary,title,topics,Video_code
0,21,TED2006,[Mena Trott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[The, founding, mother, of, the, blog, revolut...","[Meet, the, founder, of, the, blog, revolution]","[culture, design, business, entertainment, sof...",RlBTxuWCuL8
1,1,TED2006,[Al Gore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[With, the, same, humor, and, humanity, he, ex...","[Averting, the, climate, crisis]","[climate change, culture, environment, global ...",rDiGYuQicpA
2,7,TED2006,[David Pogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[New, York, Times, columnist, David, Pogue, ta...","[Simplicity, sells]","[technology, computers, entertainment, media, ...",NEjZt0y6OOw
3,47,TEDGlobal 2005,[David Deutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[Legendary, scientist, David, Deutsch, puts, t...","[Chemical, scum, that, dream, of, distant, qua...","[climate change, culture, environment, global ...",gQliI_WGaGk
4,55,TED2006,[Jehane Noujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[Jehane, Noujaim, unveils, her, 2006, TED, Pri...","[My, wish:, A, global, day, of, film]","[culture, global issues, entertainment, social...",QCFSrb6B5nw
...,...,...,...,...,...,...,...,...
5625,95500,TED2022,[Catherine Price],"[""91710"",""90821"",""76335"",""1607"",""570"",""779""]","[Have, you, had, your, daily, dose, of, fun?, ...","[Why, fun, is, the, secret, to, a, healthier, ...","[science, health, psychology, happiness, motiv...",iMBJrvEwv8s
5626,95714,TED-Ed,[Lyla Latif],"[""79294"",""24262"",""84056""]","[In, 2020,, Mali, produced, over, 71, tons, of...","[The, true, cost, of, gold]","[business, corruption, education, Africa, hist...",1nglN3mfZUw
5628,95451,TED2022,[David Wengrow],"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]","[What, if, the, commonly, accepted, narratives...","[A, new, understanding, of, human, history, an...","[culture, history, anthropology, humanity, anc...",8SJi0sHrEI4
5629,95708,TED2022,[Dan Widmaier],"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]","[Your, closet, is, likely, full, of, all, kind...","[The, future, of, fashion, --, made, from, mus...","[environment, science, sustainability, innovat...",OcdumFcGdfU
5630,95709,TED2022,[Scott Fitsimones],"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","[Could, DAOs,, or, ""decentralized, autonomous,...","[Could, a, DAO, build, the, next, great, city?]","[cities, urban planning, future, democracy, mo...",zTStDvUtQWc

In [27]:
df['speakers'] = df['speakers'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\3998127368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['speakers'] = df['speakers'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
df['topics'] = df['topics'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\835344344.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['topics'] = df['topics'].apply(lambda x:[i.replace(" ","") for i in x])

In [29]:
df.iloc[0]

ID                                                               21
event                                                       TED2006
speakers                                                [MenaTrott]
related_videos             ["144","1282","1379","87","2302","2638"]
summary           [The, founding, mother, of, the, blog, revolut...
title               [Meet, the, founder, of, the, blog, revolution]
topics            [culture, design, business, entertainment, sof...
Video_code                                              RlBTxuWCuL8
Name: 0, dtype: object

In [30]:
df['tags'] = df['speakers']+df['summary']+df['topics']
df

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\1836562364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['speakers']+df['summary']+df['topics']

,ID,event,speakers,related_videos,summary,title,topics,Video_code,tags
0,21,TED2006,[MenaTrott],"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]","[The, founding, mother, of, the, blog, revolut...","[Meet, the, founder, of, the, blog, revolution]","[culture, design, business, entertainment, sof...",RlBTxuWCuL8,"[MenaTrott, The, founding, mother, of, the, bl..."
1,1,TED2006,[AlGore],"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]","[With, the, same, humor, and, humanity, he, ex...","[Averting, the, climate, crisis]","[climatechange, culture, environment, globalis...",rDiGYuQicpA,"[AlGore, With, the, same, humor, and, humanity..."
2,7,TED2006,[DavidPogue],"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]","[New, York, Times, columnist, David, Pogue, ta...","[Simplicity, sells]","[technology, computers, entertainment, media, ...",NEjZt0y6OOw,"[DavidPogue, New, York, Times, columnist, Davi..."
3,47,TEDGlobal 2005,[DavidDeutsch],"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]","[Legendary, scientist, David, Deutsch, puts, t...","[Chemical, scum, that, dream, of, distant, qua...","[climatechange, culture, environment, globalis...",gQliI_WGaGk,"[DavidDeutsch, Legendary, scientist, David, De..."
4,55,TED2006,[JehaneNoujaim],"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]","[Jehane, Noujaim, unveils, her, 2006, TED, Pri...","[My, wish:, A, global, day, of, film]","[culture, globalissues, entertainment, socialc...",QCFSrb6B5nw,"[JehaneNoujaim, Jehane, Noujaim, unveils, her,..."
...,...,...,...,...,...,...,...,...,...
5625,95500,TED2022,[CatherinePrice],"[""91710"",""90821"",""76335"",""1607"",""570"",""779""]","[Have, you, had, your, daily, dose, of, fun?, ...","[Why, fun, is, the, secret, to, a, healthier, ...","[science, health, psychology, happiness, motiv...",iMBJrvEwv8s,"[CatherinePrice, Have, you, had, your, daily, ..."
5626,95714,TED-Ed,[LylaLatif],"[""79294"",""24262"",""84056""]","[In, 2020,, Mali, produced, over, 71, tons, of...","[The, true, cost, of, gold]","[business, corruption, education, Africa, hist...",1nglN3mfZUw,"[LylaLatif, In, 2020,, Mali, produced, over, 7..."
5628,95451,TED2022,[DavidWengrow],"[""72994"",""73025"",""91371"",""563"",""68"",""1226""]","[What, if, the, commonly, accepted, narratives...","[A, new, understanding, of, human, history, an...","[culture, history, anthropology, humanity, anc...",8SJi0sHrEI4,"[DavidWengrow, What, if, the, commonly, accept..."
5629,95708,TED2022,[DanWidmaier],"[""51538"",""83537"",""258"",""10193"",""52269"",""866""]","[Your, closet, is, likely, full, of, all, kind...","[The, future, of, fashion, --, made, from, mus...","[environment, science, sustainability, innovat...",OcdumFcGdfU,"[DanWidmaier, Your, closet, is, likely, full, ..."
5630,95709,TED2022,[ScottFitsimones],"[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]","[Could, DAOs,, or, ""decentralized, autonomous,...","[Could, a, DAO, build, the, next, great, city?]","[cities, urbanplanning, future, democracy, mon...",zTStDvUtQWc,"[ScottFitsimones, Could, DAOs,, or, ""decentral..."

In [31]:
df['tags']

0       [MenaTrott, The, founding, mother, of, the, bl...
1       [AlGore, With, the, same, humor, and, humanity...
2       [DavidPogue, New, York, Times, columnist, Davi...
3       [DavidDeutsch, Legendary, scientist, David, De...
4       [JehaneNoujaim, Jehane, Noujaim, unveils, her,...
                              ...
5625    [CatherinePrice, Have, you, had, your, daily, ...
5626    [LylaLatif, In, 2020,, Mali, produced, over, 7...
5628    [DavidWengrow, What, if, the, commonly, accept...
5629    [DanWidmaier, Your, closet, is, likely, full, ...
5630    [ScottFitsimones, Could, DAOs,, or, "decentral...
Name: tags, Length: 5462, dtype: object

In [32]:
new_df = df[['ID','tags', 'title', 'related_videos', 'Video_code']]
new_df

,ID,tags,title,related_videos,Video_code
0,21,"[MenaTrott, The, founding, mother, of, the, bl...","[Meet, the, founder, of, the, blog, revolution]","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,"[AlGore, With, the, same, humor, and, humanity...","[Averting, the, climate, crisis]","[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,"[DavidPogue, New, York, Times, columnist, Davi...","[Simplicity, sells]","[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,"[DavidDeutsch, Legendary, scientist, David, De...","[Chemical, scum, that, dream, of, distant, qua...","[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,"[JehaneNoujaim, Jehane, Noujaim, unveils, her,...","[My, wish:, A, global, day, of, film]","[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw
...,...,...,...,...,...
5625,95500,"[CatherinePrice, Have, you, had, your, daily, ...","[Why, fun, is, the, secret, to, a, healthier, ...","[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",iMBJrvEwv8s
5626,95714,"[LylaLatif, In, 2020,, Mali, produced, over, 7...","[The, true, cost, of, gold]","[""79294"",""24262"",""84056""]",1nglN3mfZUw
5628,95451,"[DavidWengrow, What, if, the, commonly, accept...","[A, new, understanding, of, human, history, an...","[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",8SJi0sHrEI4
5629,95708,"[DanWidmaier, Your, closet, is, likely, full, ...","[The, future, of, fashion, --, made, from, mus...","[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",OcdumFcGdfU
5630,95709,"[ScottFitsimones, Could, DAOs,, or, ""decentral...","[Could, a, DAO, build, the, next, great, city?]","[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]",zTStDvUtQWc

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))
new_df

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\2970228488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

,ID,tags,title,related_videos,Video_code
0,21,MenaTrott The founding mother of the blog revo...,"[Meet, the, founder, of, the, blog, revolution]","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,AlGore With the same humor and humanity he exu...,"[Averting, the, climate, crisis]","[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,DavidPogue New York Times columnist David Pogu...,"[Simplicity, sells]","[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,DavidDeutsch Legendary scientist David Deutsch...,"[Chemical, scum, that, dream, of, distant, qua...","[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,JehaneNoujaim Jehane Noujaim unveils her 2006 ...,"[My, wish:, A, global, day, of, film]","[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw
...,...,...,...,...,...
5625,95500,CatherinePrice Have you had your daily dose of...,"[Why, fun, is, the, secret, to, a, healthier, ...","[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",iMBJrvEwv8s
5626,95714,"LylaLatif In 2020, Mali produced over 71 tons ...","[The, true, cost, of, gold]","[""79294"",""24262"",""84056""]",1nglN3mfZUw
5628,95451,DavidWengrow What if the commonly accepted nar...,"[A, new, understanding, of, human, history, an...","[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",8SJi0sHrEI4
5629,95708,DanWidmaier Your closet is likely full of all ...,"[The, future, of, fashion, --, made, from, mus...","[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",OcdumFcGdfU
5630,95709,"ScottFitsimones Could DAOs, or ""decentralized ...","[Could, a, DAO, build, the, next, great, city?]","[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]",zTStDvUtQWc

In [34]:
 new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\4280305154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [35]:
# def tolow(lst):
#     L = []
#     for i in lst:
#         L.append(i.lower())
#     return lst

In [36]:
# tolow(new_df['tags'])

In [37]:
new_df

,ID,tags,title,related_videos,Video_code
0,21,menatrott the founding mother of the blog revo...,"[Meet, the, founder, of, the, blog, revolution]","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,algore with the same humor and humanity he exu...,"[Averting, the, climate, crisis]","[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,davidpogue new york times columnist david pogu...,"[Simplicity, sells]","[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,daviddeutsch legendary scientist david deutsch...,"[Chemical, scum, that, dream, of, distant, qua...","[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,jehanenoujaim jehane noujaim unveils her 2006 ...,"[My, wish:, A, global, day, of, film]","[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw
...,...,...,...,...,...
5625,95500,catherineprice have you had your daily dose of...,"[Why, fun, is, the, secret, to, a, healthier, ...","[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",iMBJrvEwv8s
5626,95714,"lylalatif in 2020, mali produced over 71 tons ...","[The, true, cost, of, gold]","[""79294"",""24262"",""84056""]",1nglN3mfZUw
5628,95451,davidwengrow what if the commonly accepted nar...,"[A, new, understanding, of, human, history, an...","[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",8SJi0sHrEI4
5629,95708,danwidmaier your closet is likely full of all ...,"[The, future, of, fashion, --, made, from, mus...","[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",OcdumFcGdfU
5630,95709,"scottfitsimones could daos, or ""decentralized ...","[Could, a, DAO, build, the, next, great, city?]","[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]",zTStDvUtQWc

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000, stop_words = 'english')

In [39]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
cv.get_feature_names()

C:\Users\Soham\.conda\envs\tensorflow\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '100',
 '11',
 '12',
 '15',
 '17',
 '19',
 '20',
 '200',
 '2007',
 '2008',
 '2011',
 '2014',
 '2016',
 '2020',
 '2050',
 '30',
 '3d',
 '40',
 '50',
 '500',
 '70',
 'ability',
 'able',
 'abuse',
 'access',
 'accessible',
 'according',
 'achieve',
 'act',
 'action',
 'actionable',
 'actions',
 'activism',
 'activist',
 'activists',
 'activity',
 'actually',
 'adam',
 'addiction',
 'addison',
 'address',
 'adrian',
 'adults',
 'advances',
 'advice',
 'advocate',
 'affairs',
 'affect',
 'affects',
 'affordable',
 'afghanistan',
 'africa',
 'african',
 'age',
 'aging',
 'ago',
 'agriculture',
 'ahead',
 'ai',
 'aid',
 'aids',
 'aim',
 'air',
 'aires',
 'al',
 'alarming',
 'alex',
 'alexander',
 'alexandra',
 'alexgendler',
 'algorithm',
 'algorithms',
 'aliens',
 'alike',
 'allow',
 'allows',
 'alternative',
 'alzheimer',
 'amazing',
 'amazon',
 'ambitious',
 'america',
 'american',
 'americans',
 'amy',
 'analysis',
 'ancestors',
 'ancient',
 'ancientworld',
 'anderson',
 'andrew',
 'andré',
 'anger',
 'animal',
 'animals',
 'animated',
 'animation',
 'anna',
 'answer',
 'answers',
 'antarctica',
 'anthropocene',
 'anthropologist',
 'anthropology',
 'anton',
 'anxiety',
 'apart',
 'app',
 'approach',
 'apps',
 'april',
 'archaeology',
 'architect',
 'architecture',
 'areas',
 'aren',
 'argues',
 'argument',
 'art',
 'artificial',
 'artist',
 'artists',
 'artrake',
 'arts',
 'asia',
 'ask',
 'asked',
 'asking',
 'asks',
 'astonishing',
 'astronomy',
 'atmosphere',
 'attack',
 'attacks',
 'attempt',
 'attention',
 'audacious',
 'audaciousproject',
 'audience',
 'audio',
 'author',
 'autism',
 'autonomous',
 'available',
 'average',
 'avi',
 'avoid',
 'away',
 'awesome',
 'babies',
 'backed',
 'bacteria',
 'bad',
 'balance',
 'bamm',
 'band',
 'based',
 'basic',
 'beautiful',
 'beauty',
 'bees',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'behavioral',
 'behavioraleconomics',
 'behaviors',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believes',
 'beloved',
 'ben',
 'benefit',
 'benefits',
 'best',
 'bestoftheweb',
 'bethany',
 'better',
 'bhayani',
 'bias',
 'big',
 'bigbang',
 'bigger',
 'biggest',
 'billion',
 'billions',
 'biodiversity',
 'bioethics',
 'biological',
 'biologist',
 'biology',
 'biomimicry',
 'biosphere',
 'biotech',
 'birds',
 'birth',
 'bit',
 'black',
 'blind',
 'blindness',
 'blockchain',
 'blood',
 'blue',
 'bodies',
 'body',
 'bogaty',
 'bold',
 'bone',
 'book',
 'books',
 'border',
 'born',
 'botany',
 'boundaries',
 'box',
 'boy',
 'brain',
 'brains',
 'brand',
 'brave',
 'brazil',
 'break',
 'breaking',
 'breaks',
 'breakthrough',
 'brian',
 'bridge',
 'brief',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'broken',
 'brooks',
 'brought',
 'brown',
 'build',
 'building',
 'buildings',
 'built',
 'business',
 'businesses',
 'buy',
 'called',
 'calling',
 'calls',
 'came',
 'camera',
 'camp',
 'campaign',
 'cancer',
 'capable',
 'capital',
 'capitalism',
 'capture',
 'car',
 'carbon',
 'care',
 'career',
 'cars',
 'case',
 'cases',
 'catch',
 'cause',
 'caused',
 'causes',
 'celebrate',
 'cell',
 'cells',
 'cem',
 'center',
 'central',
 'centuries',
 'century',
 'ceo',
 'certain',
 'cg',
 'chain',
 'challenge',
 'challenges',
 'challenging',
 'champion',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'character',
 'charles',
 'charming',
 'cheap',
 'check',
 'chemical',
 'chemistry',
 'chen',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chinese',
 'choice',
 'choices',
 'choose',
 'chris',
 'chrisanderson',
 'christina',
 'christopher',
 'cities',
 'citizen',
 'citizens',
 'city',
 'civil',
 'civilization',
 'class',
 'classic',
 'clean',
 'clear',
 'clever',
 'climate',
 'climatechange',
 'close',
 'closer',
 'code',
 'cognitive',
 'cognitivescience',
 'cold',
 'collaboration',
 'colleagues',
 'collect',
 'collection',
 'collective',
 'college',
 'color',
 'colorful',
 'com',
 'combat',
 'come',
 'comedian',
 'comedy',
 'comes',
 'comic',
 'coming',
 'common',
 'communicate',
 'communication',
 'communities',
 'community',
 'companies',
 'company',
 'compassion',
 'compelling',
 'complete',
 'completely',
 'complex',
 'complexity',
 'complicated',
 'computer',
 'computers',
 'concept',
 'concrete',
 'condition',
 'conditions',
 'conference',
 'conflict',
 'connect',
 'connected',
 'connection',
 'connections',
 'connects',
 'consciousness',
 'consequences',
 'conservation',
 'consider',
 'considered',
 'constant',
 'constantly',
 'consumerism',
 'contains',
 'content',
 'continent',
 'continue',
 'continues',
 'control',
 'controversial',
 'conversation',
 'conversations',
 'cool',
 'core',
 'coronavirus',
 'corporate',
 'corporations',
 'corruption',
 'cost',
 'costs',
 'countdown',
 'countries',
 'country',
 'course',
 'court',
 'covid',
 'cox',
 'create',
 'created',
 'creates',
 'creating',
 'creation',
 'creative',
 'creativity',
 'creatures',
 'crime',
 'criminal',
 'crisis',
 'crispr',
 'critical',
 'crucial',
 'cultural',
 'culture',
 'cultures',
 'curator',
 'cure',
 'curiosity',
 'curious',
 'current',
 'cut',
 'cutmore',
 'cutting',
 'cybersecurity',
 'cycle',
 'daily',
 'dan',
 'dance',
 'danger',
 'dangerous',
 'daniel',
 'dark',
 'data',
 'daughter',
 'david',
 'day',
 'days',
 'dead',
 'deadly',
 'deal',
 'death',
 'debate',
 'decade',
 'decades',
 'decided',
 'decision',
 'decisions',
 'deep',
 'deeper',
 'deeply',
 'define',
 'definition',
 'del',
 'deliver',
 'delivers',
 'demo',
 'democracy',
 'demonstrates',
 'demos',
 'depression',
 'describes',
 'desert',
 'design',
 'designed',
 'designer',
 'designers',
 'designing',
 'designs',
 'desire',
 'despite',
 'destruction',
 'details',
 'detect',
 'develop',
 'developed',
 'developing',
 'development',
 'device',
 'devices',
 'diagnosed',
 'did',
 'didn',
 'die',
 'difference',
 'differences',
 'different',
 'differently',
 'difficult',
 'digital',
 'dignity',
 'digs',
 'dinosaurs',
 'directed',
 'directly',
 'director',
 'disability',
 'disaster',
 'discover',
 'discovered',
 'discoveries',
 'discovery',
 'discuss',
 'discusses',
 'discussion',
 'disease',
 'diseases',
 'disorder',
 'dive',
 'diverse',
 'diversity',
 'dives',
 'divide',
 'dna',
 'doctor',
 'doctors',
 'does',
 'doesn',
 'doing',
 'dollar',
 'dollars',
 'don',
 'dr',
 'draw',
 'drawing',
 'draws',
 'dream',
 'dreams',
 'drive',
 'driven',
 'drives',
 'driving',
 'drones',
 'drug',
 'drugs',
 'dying',
 'dynamic',
 'early',
 'earth',
 'east',
 'easy',
 'eat',
 'eating',
 'ebola',
 'ecology',
 'economic',
 'economics',
 'economies',
 'economist',
 'economy',
 'ecosystems',
 'ed',
 'edge',
 'education',
 'educator',
 'effect',
 'effective',
 'effects',
 'efficient',
 'effort',
 'efforts',
 'egypt',
 'el',
 'election',
 'electric',
 'electricity',
 'elegant',
 'elements',
 'elizabeth',
 'embrace',
 'embracing',
 'emerging',
 'emily',
 'emissions',
 'emma',
 'emotional',
 'emotions',
 'empathy',
 'empire',
 'employees',
 'empower',
 'empowering',
 'en',
 'encourages',
 'encryption',
 'end',
 'endless',
 'energy',
 'engage',
 'engaging',
 'engineer',
 'engineering',
 'engineers',
 'english',
 'enormous',
 'ensure',
 'enter',
 'entertaining',
 'entertainment',
 'entire',
 'entirely',
 'entrepreneur',
 'environment',
 'environmental',
 'environments',
 'epic',
 'epidemic',
 'episode',
 'equal',
 'equality',
 'equity',
 'era',
 'eric',
 'escape',
 'especially',
 'essential',
 'ethical',
 'ethics',
 'europe',
 'event',
 'events',
 'eventually',
 'everyday',
 'evidence',
 'evolution',
 'evolutionary',
 'evolve',
 'evolved',
 'exactly',
 'examines',
 'example',
 'examples',
 'exciting',
 'executive',
 'exercise',
 'exist',
 'existence',
 'expand',
 'expanding',
 'expect',
 'expensive',
 'experience',
 'experiences',
 'experiment',
 'experiments',
 'expert',
 'explain',
 'explaining',
 'explains',
 'exploration',
 'explore',
 'explores',
 'exploring',
 'expression',
 'extraordinary',
 'extreme',
 'eye',
 'eyes',
 'face',
 'facebook',
 'facing',
 'fact',
 'factors',
 'facts',
 'fail',
 'failure',
 'fair',
 'faith',
 'fall',
 'familiar',
 'families',
 'family',
 'famous',
 'far',
 'farkas',
 'farmers',
 'farming',
 'fascinating',
 'fashion',
 'fast',
 'faster',
 'father',
 'favorite',
 'fear',
 'features',
 'feed',
 'feel',
 'feeling',
 'feelings',
 'fellow',
 'felt',
 'female',
 'feminism',
 'fiction',
 'field',
 'fight',
 'fighting',
 'figure',
 'filled',
 'film',
 'filmmaker',
 'films',
 'finally',
 'finance',
 'financial',
 'finding',
 'findings',
 'finkel',
 'fish',
 'fit',
 'fix',
 'flight',
 'fly',
 'flying',
 'focus',
 'focused',
 'follow',
 'followed',
 'following',
 'follows',
 'food',
 'footage',
 'force',
 'forced',
 'forces',
 'forever',
 'form',
 'forms',
 'forward',
 'fossil',
 'foster',
 'foundation',
 'founder',
 'free',
 'freedom',
 'fresh',
 'friend',
 'friendly',
 'friends',
 'friendship',
 'fuel',
 'fully',
 'fun',
 'fund',
 'fundamental',
 'fungi',
 'funny',
 'future',
 'gabriel',
 'game',
 'games',
 'gaming',
 'gap',
 'gardening',
 'gas',
 'gave',
 'gay',
 'gender',
 'gendler',
 'general',
 'generation',
 'generations',
 'genetic',
 'genetics',
 'george',
 'gets',
 'getting',
 'giant',
 'gillespie',
 'girl',
 'girls',
 'given',
 'gives',
 'giving',
 'glass',
 'glimpse',
 'global',
 'globalissues',
 'globe',
 'goal',
 'goals',
 'god',
 'goes',
 'going',
 'gold',
 'good',
 'google',
 'gore',
 'got',
 'government',
 'governments',
 'graphic',
 'great',
 'greater',
 'greatest',
 'green',
 'greer',
 'grew',
 'ground',
 'groundbreaking',
 'group',
 'groups',
 'grow',
 'growing',
 'grown',
 'growth',
 'guide',
 'guitar',
 'habits',
 'hair',
 'half',
 'hand',
 'hands',
 'happen',
 'happened',
 'happening',
 'happens',
 'happiness',
 'happy',
 'hard',
 'harm',
 'harness',
 'hate',
 'haven',
 'having',
 'head',
 'heal',
 'health',
 'healthcare',
 'healthy',
 'hear',
 'heard',
 'hearing',
 'heart',
 'heartfelt',
 'heat',
 'helen',
 'help',
 'helped',
 'helping',
 'helps',
 'hidden',
 'high',
 'higher',
 'highlights',
 'hilarious',
 'historian',
 'historical',
 'history',
 'hit',
 'hiv',
 'hold',
 'holding',
 'hole',
 'home',
 'homes',
 'honest',
 'honor',
 'hope',
 'hopeful',
 'hopes',
 'hospital',
 'host',
 'hosted',
 'hour',
 'hours',
 'house',
 'huge',
 'human',
 'humanbody',
 'humanity',
 'humanrights',
 'humans',
 'humor',
 'hundreds',
 'hype',
 'ice',
 'iconic',
 'idea',
 'ideas',
 'identifies',
 'identify',
 'identity',
 'igor',
 'illness',
 'illuminating',
 'illusion',
 'illustrate',
 'image',
 'images',
 'imagination',
 'imagine',
 'imagines',
 'immigration',
 'immune',
 'impact',
 'impacts',
 'implications',
 'importance',
 'important',
 'impossible',
 'improve',
 'include',
 'including',
 'inclusion',
 'inclusive',
 'income',
 'increase',
 'increasingly',
 'incredible',
 'india',
 'indigenous',
 'indigenouspeoples',
 'individual',
 'individuals',
 'industrial',
 'industrialdesign',
 'industry',
 'inequality',
 'influence',
 'information',
 'informative',
 'infrastructure',
 'initiative',
 'inner',
 'innovation',
 'innovations',
 'innovative',
 'insects',
 'inside',
 'insight',
 'insightful',
 'insights',
 'inspiration',
 'inspire',
 'inspired',
 'inspiring',
 'instead',
 'institutions',
 'intelligence',
 'interact',
 'interesting',
 'international',
 'internationaldevelopment',
 'internet',
 'interview',
 'intimate',
 'intriguing',
 'introduces',
 'invented',
 'invention',
 'inventor',
 'investigates',
 'investing',
 'investment',
 'invisible',
 'invites',
 'involved',
 'iseult',
 'iseultgillespie',
 'island',
 'isn',
 'issue',
 'issues',
 'jack',
 'james',
 'jane',
 'jarrett',
 'jeff',
 'jennifer',
 'jessica',
 'job',
 'jobs',
 'john',
 'johnson',
 'join',
 'jonathan',
 'jones',
 'joseph',
 'joshua',
 'journalism',
 'journalist',
 'journey',
 'joy',
 'june',
 'just',
 'justice',
 'justicesystem',
 'kate',
 'keeping',
 'kevin',
 ...]

In [43]:
import nltk

In [44]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [45]:
def stem(text):
    y = []
    for i in text.split(): 
        y.append(ps.stem(i))
    
    return " ".join(y)

In [46]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [47]:
new_df

,ID,tags,title,related_videos,Video_code
0,21,menatrott the found mother of the blog revolut...,"[Meet, the, founder, of, the, blog, revolution]","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,algor with the same humor and human he exud in...,"[Averting, the, climate, crisis]","[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,davidpogu new york time columnist david pogu t...,"[Simplicity, sells]","[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,daviddeutsch legendari scientist david deutsch...,"[Chemical, scum, that, dream, of, distant, qua...","[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,jehanenoujaim jehan noujaim unveil her 2006 te...,"[My, wish:, A, global, day, of, film]","[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw
...,...,...,...,...,...
5625,95500,catherinepric have you had your daili dose of ...,"[Why, fun, is, the, secret, to, a, healthier, ...","[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",iMBJrvEwv8s
5626,95714,"lylalatif in 2020, mali produc over 71 ton of ...","[The, true, cost, of, gold]","[""79294"",""24262"",""84056""]",1nglN3mfZUw
5628,95451,davidwengrow what if the commonli accept narr ...,"[A, new, understanding, of, human, history, an...","[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",8SJi0sHrEI4
5629,95708,danwidmai your closet is like full of all kind...,"[The, future, of, fashion, --, made, from, mus...","[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",OcdumFcGdfU
5630,95709,"scottfitsimon could daos, or ""decentr autonom ...","[Could, a, DAO, build, the, next, great, city?]","[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]",zTStDvUtQWc

In [48]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [49]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])[1:6]

[(2509, 0.2913971185543097),
 (1713, 0.2910427500435996),
 (279, 0.28),
 (4140, 0.27136021011998723),
 (190, 0.2618614682831909)]

In [50]:
def recommend(video):
    ted_index = new_df[new_df['title'] == video].index[0]
    distances = similarity[ted_index]
    ted_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    
    for i in ted_list:
        print(new_df.iloc[i[0]].title)

In [51]:
# new_df['title'] = new_df['title'].apply(lambda x:" ".join(x))

In [52]:
new_df['title'].tail()

5625    [Why, fun, is, the, secret, to, a, healthier, ...
5626                          [The, true, cost, of, gold]
5628    [A, new, understanding, of, human, history, an...
5629    [The, future, of, fashion, --, made, from, mus...
5630      [Could, a, DAO, build, the, next, great, city?]
Name: title, dtype: object

In [53]:
new_df

,ID,tags,title,related_videos,Video_code
0,21,menatrott the found mother of the blog revolut...,"[Meet, the, founder, of, the, blog, revolution]","[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,algor with the same humor and human he exud in...,"[Averting, the, climate, crisis]","[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,davidpogu new york time columnist david pogu t...,"[Simplicity, sells]","[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,daviddeutsch legendari scientist david deutsch...,"[Chemical, scum, that, dream, of, distant, qua...","[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,jehanenoujaim jehan noujaim unveil her 2006 te...,"[My, wish:, A, global, day, of, film]","[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw
...,...,...,...,...,...
5625,95500,catherinepric have you had your daili dose of ...,"[Why, fun, is, the, secret, to, a, healthier, ...","[""91710"",""90821"",""76335"",""1607"",""570"",""779""]",iMBJrvEwv8s
5626,95714,"lylalatif in 2020, mali produc over 71 ton of ...","[The, true, cost, of, gold]","[""79294"",""24262"",""84056""]",1nglN3mfZUw
5628,95451,davidwengrow what if the commonli accept narr ...,"[A, new, understanding, of, human, history, an...","[""72994"",""73025"",""91371"",""563"",""68"",""1226""]",8SJi0sHrEI4
5629,95708,danwidmai your closet is like full of all kind...,"[The, future, of, fashion, --, made, from, mus...","[""51538"",""83537"",""258"",""10193"",""52269"",""866""]",OcdumFcGdfU
5630,95709,"scottfitsimon could daos, or ""decentr autonom ...","[Could, a, DAO, build, the, next, great, city?]","[""84954"",""89893"",""91980"",""2107"",""1429"",""66946""]",zTStDvUtQWc

In [54]:
new_df['title'] = new_df['title'].apply(lambda x:" ".join(x))

C:\Users\Soham\AppData\Local\Temp\ipykernel_15968\3261798338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title'] = new_df['title'].apply(lambda x:" ".join(x))

In [55]:
recommend('My wish: A global day of film')

A tour of Nollywood, Nigeria's booming film industry
My journey into movies that matter
How film transforms the way we see the world
The story of Ezra
The pride and power of representation in film

In [56]:
import pickle

In [57]:
pickle.dump(new_df,open('video_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [58]:
new_df.head()

,ID,tags,title,related_videos,Video_code
0,21,menatrott the found mother of the blog revolut...,Meet the founder of the blog revolution,"[""144"",""1282"",""1379"",""87"",""2302"",""2638""]",RlBTxuWCuL8
1,1,algor with the same humor and human he exud in...,Averting the climate crisis,"[""243"",""547"",""2093"",""74405"",""64693"",""83767""]",rDiGYuQicpA
2,7,davidpogu new york time columnist david pogu t...,Simplicity sells,"[""1725"",""2274"",""172"",""2664"",""2464"",""1268""]",NEjZt0y6OOw
3,47,daviddeutsch legendari scientist david deutsch...,Chemical scum that dream of distant quasars,"[""2237"",""701"",""1095"",""1386"",""76211"",""242""]",gQliI_WGaGk
4,55,jehanenoujaim jehan noujaim unveil her 2006 te...,My wish: A global day of film,"[""2228"",""1476"",""800"",""2890"",""45233"",""2694""]",QCFSrb6B5nw

In [61]:
new_df.iloc[0].Video_code

'RlBTxuWCuL8'